version: '3.4'

services:
  cdatabase:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: correlation
    ports:
      - "54320:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "postgres"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - default

  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - '4160:4160'
      - '4161:4161'
    networks:
      - default

  nsqd:
    image: nsqio/nsq
    command: /nsqd --broadcast-address=nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - '4150:4150'
      - '4151:4151'
    networks:
      - default

  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - '4171:4171'
    networks:
      - default

  aggregator:
    image: bdc/aggregator
    build:
      context: .
      dockerfile: aggregator/Dockerfile
    networks:
      - default
    ports:
      - '8080:8080'
    depends_on:
      - nsqd

  correlation:
    image: bdc/correlation
    build:
      context: .
      dockerfile: correlation/Dockerfile
    networks:
      - default
    depends_on:
      - cdatabase
      - aggregator
      - nsqd

  device:
    image: bdc/device
    build:
      context: .
      dockerfile: device/Dockerfile
    networks:
      - default
    depends_on:
      - aggregator
      - correlation
      - nsqd

networks:
  default:
