version: '3.4'

services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - '4160:4160'
      - '4161:4161'
    networks:
      - default

  nsqd:
    image: nsqio/nsq
    command: /nsqd --broadcast-address=nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - '4150:4150'
      - '4151:4151'
    networks:
      - default

  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - '4171:4171'
    networks:
      - default

  aggregator:
    image: bdc/aggregator
    build:
      context: .
      dockerfile: aggregator/Dockerfile
    networks:
      - default
    ports:
      - '8080:8080'
    depends_on:
      - nsqd

  correlation:
    image: bdc/correlation
    build:
      context: .
      dockerfile: correlation/Dockerfile
    networks:
      - default
    depends_on:
      - aggregator
      - nsqd

  device:
    image: bdc/device
    build:
      context: .
      dockerfile: device/Dockerfile
    networks:
      - default
    depends_on:
      - aggregator
      - correlation
      - nsqd

networks:
  default:
